### ISSUE TITLE
Add documentation for tsne visualisation to docs (README.md)

### ISSUE THREAD

**Issue by tiadams** [SCAI-BIO/datastew#29]
Following issue #27:

- [ ]  Add code sample for test dictionaries in documentation (README.md)
- [ ] Add a plot vor a simple example, showcasing the plotly plot (howering over a single datapoint for labels)

**Comment by tiadams** [comment]
On that note: Maybe makes sense to have a more expressive example for the test file than [the current one](https://github.com/SCAI-BIO/datastew/blob/main/tests/test_visualisation.py#L132) in case we want to use it for documentation.

**Comment by mehmetcanay** [comment]
> On that note: Maybe makes sense to have a more expressive example for the test file than [the current one](https://github.com/SCAI-BIO/datastew/blob/main/tests/test_visualisation.py#L132) in case we want to use it for documentation.

I already host the translated version of BIOFIND cohort on GitHub publicly. Does it make sense to utilize that?
