### ISSUE TITLE
PR #95 failed

### ISSUE THREAD

**Issue by tiadams** [SCAI-BIO/datastew#48]
https://github.com/SCAI-BIO/datastew/actions/runs/11488011609

Failed for python 3.9 after the data dictionary merge, could you look into that @mehmetcanay ?

**Comment by mehmetcanay** [comment]
One possible solution we can implement is to adjust gRPC timeout: https://weaviate.io/developers/weaviate/connections/connect-cloud

**Comment by mehmetcanay** [comment]
Another alternative is switching to the `AsyncWeaviateClient`, but I doubt this will solve it.
